site_name: PyMT4 SDK Documentation
site_url: https://metarpc.github.io/PyMT4/
site_description: Complete Python SDK for MetaTrader 4 trading automation

repo_name: MetaRPC/PyMT4
repo_url: https://github.com/MetaRPC/PyMT4
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    logo: material/chart-line-variant
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.footer
    - content.code.copy
    - toc.follow

extra:
  # Баннер под шапкой — панель быстрого доступа (будет на всех страницах)
  announcement: |
    <nav class="quickbar quickbar--banner">
      <a class="quickbar-item home" href="{{ base_url }}/">
        <span class="material-symbols-rounded">home</span><span>Home</span>
      </a>
      <a class="quickbar-item" href="{{ base_url }}/MT4Account/Account_Information/account_summary/">Account Info</a>
      <a class="quickbar-item" href="{{ base_url }}/MT4Account/Market_quota_symbols/Market_Quota.Overview/">Market Quota</a>
      <a class="quickbar-item" href="{{ base_url }}/MT4Account/Orders_Positions_History/Positions_History_Overview/">Positions History</a>
      <a class="quickbar-item" href="{{ base_url }}/MT4Account/Streams/Streams_Overview/">Streams</a>
      <a class="quickbar-item" href="{{ base_url }}/MT4Account/Trading_Actions/Trading_Actions_Overview/">Trading Actions</a>
      <span class="quickbar-sep"></span>
      <a class="quickbar-item" href="{{ base_url }}/api/">API</a>
      <a class="quickbar-item" href="{{ base_url }}/configuration/">Reference</a>
    </nav>
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MetaRPC/PyMT4
      name: PyMT4 on GitHub

extra_css:
  - styles/custom.css

extra_javascript:
  - javascripts/ux.js

markdown_extensions:
  - admonition
  - md_in_html
  - tables
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "¶"
      toc_depth: 3

plugins:
  - search

copyright: >
  Copyright © 2024–2025 MetaRPC. MT4 is a trademark of MetaQuotes Software Corp.
  This documentation is community-maintained and not affiliated with MetaQuotes.

nav:
  - Home: index.md

  - Quick Access:
    - Account Info: MT4Account/Account_Information/account_summary.md
    - Market Quota — Overview: MT4Account/Market_quota_symbols/Market_Quota.Overview.md
    - Positions History — Overview: MT4Account/Orders_Positions_History/Positions_History_Overview.md
    - Streams — Overview: MT4Account/Streams/Streams_Overview.md
    - Trading Actions — Overview: MT4Account/Trading_Actions/Trading_Actions_Overview.md
    - API: api.md

  - Guides:
    - BASE: MT4Account/BASE.md
    - Project Map: PROJECT_MAP.md
    - Architecture: ARCHITECTURE.md
    - MT4Sugar — Overview: MT4Sugar/Overview.md
    - Main — Overview: Main/Overview.md
    - Glossary: GLOSSARY.md
    - Examples — Overview: Examples/All_about_examples.md
    - Orchestrator — Overview: Strategy/All_about_orchestrator.md
    - Presets — Overview: Strategy/All_about_presets.md
    - API Documentation: api.md
