site_name: MetaRPC MT4 Python Documentation
site_url: https://metarpc.github.io/PyMT4/

repo_name: MetaRPC/PyMT5
repo_url: https://github.com/MetaRPC/PyMT4
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    logo: material/robot-industrial
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - search.highlight
    - search.suggest
    - palette.toggle
    - palette.auto

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MetaRPC/PyMT4
      name: GitHub
  generator: false
  consent:
    title: Cookies & telemetry
    description: We use GitHub Pages basic analytics only. No tracking cookies.
  announcement: >
    Welcome! These docs are evolving. PRs are very welcome.

copyright: >
  © {{ date | strftime("%Y") }} MetaRPC. MT5 is a MetaQuotes software. This site is a community-made documentation.

nav:
  - Home: index.md
  - API: api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - abbr
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      prebuild_index: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            members_order: source
            filters: ["!^_"]

extra_css:
  - styles/overrides.css
