# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mt4_term_api_gui_pb2 as mt4__term__api__gui__pb2


class GuiStub(object):
    """Terminal-side GUI-automation service (implemented by mt4-framework-grpc, which
    P/Invokes mt4-term-gui.dll). The manager's DemoAccount service proxies to these.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DemoFindCompanies = channel.unary_unary(
                '/mt4_term_api.Gui/DemoFindCompanies',
                request_serializer=mt4__term__api__gui__pb2.GuiDemoFindCompaniesRequest.SerializeToString,
                response_deserializer=mt4__term__api__gui__pb2.GuiDemoFindCompaniesReply.FromString,
                )
        self.DemoServersAndTypes = channel.unary_unary(
                '/mt4_term_api.Gui/DemoServersAndTypes',
                request_serializer=mt4__term__api__gui__pb2.GuiDemoServersAndTypesRequest.SerializeToString,
                response_deserializer=mt4__term__api__gui__pb2.GuiDemoServersAndTypesReply.FromString,
                )
        self.DemoOpenAccount = channel.unary_unary(
                '/mt4_term_api.Gui/DemoOpenAccount',
                request_serializer=mt4__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
                response_deserializer=mt4__term__api__gui__pb2.GuiDemoOpenAccountReply.FromString,
                )
        self.DemoOpenAccountWithProgress = channel.unary_stream(
                '/mt4_term_api.Gui/DemoOpenAccountWithProgress',
                request_serializer=mt4__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
                response_deserializer=mt4__term__api__gui__pb2.GuiDemoProgressEvent.FromString,
                )


class GuiServicer(object):
    """Terminal-side GUI-automation service (implemented by mt4-framework-grpc, which
    P/Invokes mt4-term-gui.dll). The manager's DemoAccount service proxies to these.
    """

    def DemoFindCompanies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DemoServersAndTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DemoOpenAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DemoOpenAccountWithProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DemoFindCompanies': grpc.unary_unary_rpc_method_handler(
                    servicer.DemoFindCompanies,
                    request_deserializer=mt4__term__api__gui__pb2.GuiDemoFindCompaniesRequest.FromString,
                    response_serializer=mt4__term__api__gui__pb2.GuiDemoFindCompaniesReply.SerializeToString,
            ),
            'DemoServersAndTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.DemoServersAndTypes,
                    request_deserializer=mt4__term__api__gui__pb2.GuiDemoServersAndTypesRequest.FromString,
                    response_serializer=mt4__term__api__gui__pb2.GuiDemoServersAndTypesReply.SerializeToString,
            ),
            'DemoOpenAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DemoOpenAccount,
                    request_deserializer=mt4__term__api__gui__pb2.GuiDemoOpenAccountRequest.FromString,
                    response_serializer=mt4__term__api__gui__pb2.GuiDemoOpenAccountReply.SerializeToString,
            ),
            'DemoOpenAccountWithProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.DemoOpenAccountWithProgress,
                    request_deserializer=mt4__term__api__gui__pb2.GuiDemoOpenAccountRequest.FromString,
                    response_serializer=mt4__term__api__gui__pb2.GuiDemoProgressEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt4_term_api.Gui', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Gui(object):
    """Terminal-side GUI-automation service (implemented by mt4-framework-grpc, which
    P/Invokes mt4-term-gui.dll). The manager's DemoAccount service proxies to these.
    """

    @staticmethod
    def DemoFindCompanies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt4_term_api.Gui/DemoFindCompanies',
            mt4__term__api__gui__pb2.GuiDemoFindCompaniesRequest.SerializeToString,
            mt4__term__api__gui__pb2.GuiDemoFindCompaniesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DemoServersAndTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt4_term_api.Gui/DemoServersAndTypes',
            mt4__term__api__gui__pb2.GuiDemoServersAndTypesRequest.SerializeToString,
            mt4__term__api__gui__pb2.GuiDemoServersAndTypesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DemoOpenAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt4_term_api.Gui/DemoOpenAccount',
            mt4__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
            mt4__term__api__gui__pb2.GuiDemoOpenAccountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DemoOpenAccountWithProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mt4_term_api.Gui/DemoOpenAccountWithProgress',
            mt4__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
            mt4__term__api__gui__pb2.GuiDemoProgressEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
