# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mt4_term_api_demo_account_pb2 as mt4__term__api__demo__account__pb2
from . import mt4_term_api_gui_pb2 as mt4__term__api__gui__pb2


class DemoAccountStub(object):
    """Demo account creation service. Automates the MT4 "Open an Account" wizard via
    Win32 GUI automation (proxied to the terminal's Gui service).
    Does NOT require 'id' header — auto-picks any available terminal.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindCompanies = channel.unary_unary(
                '/mt4_term_api.DemoAccount/FindCompanies',
                request_serializer=mt4__term__api__gui__pb2.GuiDemoFindCompaniesRequest.SerializeToString,
                response_deserializer=mt4__term__api__gui__pb2.GuiDemoFindCompaniesReply.FromString,
                )
        self.ServersAndAccountTypes = channel.unary_unary(
                '/mt4_term_api.DemoAccount/ServersAndAccountTypes',
                request_serializer=mt4__term__api__gui__pb2.GuiDemoServersAndTypesRequest.SerializeToString,
                response_deserializer=mt4__term__api__gui__pb2.GuiDemoServersAndTypesReply.FromString,
                )
        self.OpenDemoAccount = channel.unary_unary(
                '/mt4_term_api.DemoAccount/OpenDemoAccount',
                request_serializer=mt4__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
                response_deserializer=mt4__term__api__gui__pb2.GuiDemoOpenAccountReply.FromString,
                )
        self.OpenDemoAccountStream = channel.unary_stream(
                '/mt4_term_api.DemoAccount/OpenDemoAccountStream',
                request_serializer=mt4__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
                response_deserializer=mt4__term__api__demo__account__pb2.DemoAccountStreamEvent.FromString,
                )


class DemoAccountServicer(object):
    """Demo account creation service. Automates the MT4 "Open an Account" wizard via
    Win32 GUI automation (proxied to the terminal's Gui service).
    Does NOT require 'id' header — auto-picks any available terminal.
    """

    def FindCompanies(self, request, context):
        """Search for broker companies by name (reads the wizard's broker ListView).
        [DefaultValues]
        { "searchText": "MetaQuotes" }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServersAndAccountTypes(self, request, context):
        """Get available servers and account types for a company.
        [DefaultValues]
        { "companyName": "MetaQuotes Ltd." }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenDemoAccount(self, request, context):
        """Open a demo account. Full wizard flow: search -> select -> fill form -> register.
        [DefaultValues]
        { "company": "MetaQuotes Ltd.", "firstName": "Test", "lastName": "User",
        "email": "test@test.com", "phone": "+1234567890", "timeoutSeconds": "60" }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenDemoAccountStream(self, request, context):
        """Same as OpenDemoAccount but streams real-time progress events.
        Swagger does not support streaming — use /demo-account-stream interactive viewer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoAccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindCompanies': grpc.unary_unary_rpc_method_handler(
                    servicer.FindCompanies,
                    request_deserializer=mt4__term__api__gui__pb2.GuiDemoFindCompaniesRequest.FromString,
                    response_serializer=mt4__term__api__gui__pb2.GuiDemoFindCompaniesReply.SerializeToString,
            ),
            'ServersAndAccountTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ServersAndAccountTypes,
                    request_deserializer=mt4__term__api__gui__pb2.GuiDemoServersAndTypesRequest.FromString,
                    response_serializer=mt4__term__api__gui__pb2.GuiDemoServersAndTypesReply.SerializeToString,
            ),
            'OpenDemoAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenDemoAccount,
                    request_deserializer=mt4__term__api__gui__pb2.GuiDemoOpenAccountRequest.FromString,
                    response_serializer=mt4__term__api__gui__pb2.GuiDemoOpenAccountReply.SerializeToString,
            ),
            'OpenDemoAccountStream': grpc.unary_stream_rpc_method_handler(
                    servicer.OpenDemoAccountStream,
                    request_deserializer=mt4__term__api__gui__pb2.GuiDemoOpenAccountRequest.FromString,
                    response_serializer=mt4__term__api__demo__account__pb2.DemoAccountStreamEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt4_term_api.DemoAccount', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DemoAccount(object):
    """Demo account creation service. Automates the MT4 "Open an Account" wizard via
    Win32 GUI automation (proxied to the terminal's Gui service).
    Does NOT require 'id' header — auto-picks any available terminal.
    """

    @staticmethod
    def FindCompanies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt4_term_api.DemoAccount/FindCompanies',
            mt4__term__api__gui__pb2.GuiDemoFindCompaniesRequest.SerializeToString,
            mt4__term__api__gui__pb2.GuiDemoFindCompaniesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServersAndAccountTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt4_term_api.DemoAccount/ServersAndAccountTypes',
            mt4__term__api__gui__pb2.GuiDemoServersAndTypesRequest.SerializeToString,
            mt4__term__api__gui__pb2.GuiDemoServersAndTypesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenDemoAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt4_term_api.DemoAccount/OpenDemoAccount',
            mt4__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
            mt4__term__api__gui__pb2.GuiDemoOpenAccountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenDemoAccountStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mt4_term_api.DemoAccount/OpenDemoAccountStream',
            mt4__term__api__gui__pb2.GuiDemoOpenAccountRequest.SerializeToString,
            mt4__term__api__demo__account__pb2.DemoAccountStreamEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
